backend: vgg16
dataset_name: cifar10
checkpoint_dir: checkpoints/vgg16_training
seed: !!int 2

do_train: true
do_eval: true

# Training option
train:
    batch_size: 64
    max_epoch: 300



optimizer:
    name: hspg
    init_stage: sgd
    init_lr: 0.1
    n_p: 150
    lambda: !!float 1e-3
    decay_mode: multi_step
    decays: [75, 130, 150]
    momentum: 0.4
    epsilon: [0.0, 0.0, 0.0, 0.0, 0.0]
    upper_group_sparsity: [1.0, 1.0, 1.0, 1.0, 1.0]
